const express=require('express');
const path=require('path');
const app=express();
app.use(express.json());
const seed={profile:{name:'陈小雨',education:'本科大三',gpa:'3.5/4.0',english:'IELTS 6.5',budget:'25万/年',country:'新加坡 / 英国',completion:72},programs:[{id:1,school:'南洋国际学院（演示）',country:'新加坡',program:'数据科学硕士',degree:'硕士',lang:'IELTS 6.5',fee:188000,scholarship:30000,deadline:'2026-11-30',fit:'符合已知条件'},{id:2,school:'海峡商学院（演示）',country:'新加坡',program:'国际商务本科',degree:'本科',lang:'IELTS 6.0',fee:128000,scholarship:20000,deadline:'2026-12-15',fit:'资料不足'},{id:3,school:'英伦创新大学（演示）',country:'英国',program:'金融科技硕士',degree:'硕士',lang:'IELTS 6.5',fee:236000,scholarship:25000,deadline:'2027-01-20',fit:'符合已知条件'}],clients:[{id:101,name:'陈小雨',source:'机构专属二维码',owner:'王老师',stage:'材料准备',completion:82},{id:102,name:'李晨',source:'自然注册后授权',owner:'周老师',stage:'院校受理',completion:91}],applications:[{id:'APP-260901',student:'陈小雨',programId:1,agency:'环球学桥（演示）',school:'南洋国际学院（演示）',status:'材料准备',progress:42,commission:9800},{id:'APP-260823',student:'李晨',programId:3,agency:'环球学桥（演示）',school:'英伦创新大学（演示）',status:'院校受理',progress:68,commission:12500}],audits:[{id:1,type:'奖学金',name:'2027春季优秀新生减免',org:'海峡商学院（演示）',status:'待审核'},{id:2,type:'机构认证',name:'新加坡启航教育（演示）',org:'B端机构',status:'待审核'}]};
let db=JSON.parse(JSON.stringify(seed));
const ok=data=>({ok:true,data});
app.get('/api/health',(req,res)=>res.json(ok({status:'ok',service:'global-study-mobile-mvp'})));
app.get('/api/bootstrap',(req,res)=>res.json(ok(db)));
app.post('/api/applications',(req,res)=>{const p=db.programs.find(x=>x.id===Number(req.body.programId));if(!p)return res.status(400).json({ok:false,error:'项目不存在'});if(db.applications.some(a=>a.student===req.body.student&&a.programId===p.id))return res.status(409).json({ok:false,error:'该项目已申请'});const x={id:'APP-'+Date.now().toString().slice(-6),student:req.body.student,programId:p.id,agency:req.body.agency||'待授权机构',school:p.school,status:'材料准备',progress:18,commission:Math.round(p.fee*.05)};db.applications.unshift(x);res.status(201).json(ok(x))});
app.patch('/api/applications/:id',(req,res)=>{const x=db.applications.find(a=>a.id===req.params.id);if(!x)return res.status(404).json({ok:false,error:'申请不存在'});Object.assign(x,req.body);res.json(ok(x))});
app.post('/api/clients',(req,res)=>{if(!req.body.name)return res.status(400).json({ok:false,error:'姓名必填'});const x={id:Date.now(),name:req.body.name,source:'机构专属邀请',owner:req.body.owner||'王老师',stage:'待建档',completion:10};db.clients.unshift(x);res.status(201).json(ok(x))});
app.patch('/api/audits/:id',(req,res)=>{const x=db.audits.find(a=>a.id===Number(req.params.id));if(!x)return res.status(404).json({ok:false,error:'审核事项不存在'});x.status=req.body.status||x.status;res.json(ok(x))});
app.use(express.static(path.join(__dirname,'public')));
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
app.listen(process.env.PORT||3000,()=>console.log('GlobalStudy MVP running'));
